### ISSUE TITLE
The jetty docker image leaks slf4j impl to the webapp

### ISSUE THREAD

**Issue by vmassol** [eclipse/jetty.docker#118]
**Jetty version(s)**
10.0.12

**Description**
XWiki has a webapp that contains slf4j and we've upgraded to version 2.0.0. This is causing a failure to start the official jetty docker image (tag `10-jdk11`), with the following error (see https://jira.xwiki.org/browse/XWIKI-20131 too):

```
2022-09-27 11:24:28.402:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@20b2475a{XWiki,/xwiki,[file:///Users/vmassol/Desktop/jetty/jetty-base/webapps/xwiki/, ...}
java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: Provider org.eclipse.jetty.logging.JettyLoggingServiceProvider not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
	at org.xwiki.container.servlet.XWikiServletContextListener.<clinit>(XWikiServletContextListener.java:50)
```

We are able to start the jetty from the standard jetty zip withoot any problem when using `java -jar $JETTY_HOME/start.jar`.

The issue is that the docker image [runs `docker-entrypoint.sh`](https://github.com/eclipse/jetty.docker/blob/master/eclipse-temurin/10.0/jdk11/Dockerfile#L96) which calls [`generate-jetty-start.sh`](https://github.com/eclipse/jetty.docker/blob/master/eclipse-temurin/10.0/jdk11/generate-jetty-start.sh) and which generates a `jetty.start` file which, when executed causes the failure to deploy the xwiki webapp with the stacktrace from above.

FYI the generated `jetty.start` is:

```
/opt/java/openjdk/bin/java -Djetty.home=/usr/local/jetty -Djetty.base=/var/lib/jetty --class-path /var/lib/jetty/resources:/usr/local/jetty/lib/logging/slf4j-api-2.0.0.jar:/usr/local/jetty/lib/logging/jetty-slf4j-impl-10.0.12.jar:/usr/local/jetty/lib/jetty-servlet-api-4.0.6.jar:/usr/local/jetty/lib/jetty-http-10.0.12.jar:/usr/local/jetty/lib/jetty-server-10.0.12.jar:/usr/local/jetty/lib/jetty-xml-10.0.12.jar:/usr/local/jetty/lib/jetty-util-10.0.12.jar:/usr/local/jetty/lib/jetty-io-10.0.12.jar:/usr/local/jetty/lib/jetty-jndi-10.0.12.jar:/usr/local/jetty/lib/jetty-security-10.0.12.jar:/usr/local/jetty/lib/jetty-servlet-10.0.12.jar:/usr/local/jetty/lib/jetty-webapp-10.0.12.jar:/usr/local/jetty/lib/jetty-plus-10.0.12.jar:/usr/local/jetty/lib/jakarta.transaction-api-1.3.3.jar:/usr/local/jetty/lib/jetty-annotations-10.0.12.jar:/usr/local/jetty/lib/annotations/asm-9.3.jar:/usr/local/jetty/lib/annotations/asm-analysis-9.3.jar:/usr/local/jetty/lib/annotations/asm-commons-9.3.jar:/usr/local/jetty/lib/annotations/asm-tree-9.3.jar:/usr/local/jetty/lib/annotations/jakarta.annotation-api-1.3.5.jar:/usr/local/jetty/lib/apache-jsp/org.eclipse.jdt.ecj-3.26.0.jar:/usr/local/jetty/lib/apache-jsp/org.eclipse.jetty.apache-jsp-10.0.12.jar:/usr/local/jetty/lib/apache-jsp/org.mortbay.jasper.apache-el-9.0.52.jar:/usr/local/jetty/lib/apache-jsp/org.mortbay.jasper.apache-jsp-9.0.52.jar:/usr/local/jetty/lib/apache-jstl/org.apache.taglibs.taglibs-standard-impl-1.2.5.jar:/usr/local/jetty/lib/apache-jstl/org.apache.taglibs.taglibs-standard-spec-1.2.5.jar:/usr/local/jetty/lib/jetty-client-10.0.12.jar:/usr/local/jetty/lib/jetty-alpn-client-10.0.12.jar:/usr/local/jetty/lib/jetty-deploy-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-core-common-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-core-client-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-core-server-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-servlet-10.0.12.jar:/usr/local/jetty/lib/websocket/jetty-javax-websocket-api-1.1.2.jar:/usr/local/jetty/lib/websocket/websocket-javax-client-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-javax-common-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-javax-server-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-jetty-api-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-jetty-common-10.0.12.jar:/usr/local/jetty/lib/websocket/websocket-jetty-server-10.0.12.jar org.eclipse.jetty.xml.XmlConfiguration java.version=11.0.16.1 java.version.major=11 java.version.micro=16 java.version.minor=0 java.version.platform=11 jetty.base=/var/lib/jetty jetty.base.uri=file:///var/lib/jetty jetty.home=/usr/local/jetty jetty.home.uri=file:///usr/local/jetty jetty.webapp.addServerClasses=org.eclipse.jetty.logging.,${jetty.home.uri}/lib/logging/,org.slf4j. runtime.feature.alpn=true slf4j.version=2.0.0 /usr/local/jetty/etc/jetty-bytebufferpool.xml /usr/local/jetty/etc/jetty-threadpool.xml /usr/local/jetty/etc/jetty.xml /usr/local/jetty/etc/jetty-webapp.xml /usr/local/jetty/etc/jetty-deploy.xml /usr/local/jetty/etc/jetty-http.xml
```

Related:
* https://github.com/eclipse/jetty.project/issues/6112
* https://github.com/eclipse/jetty.project/commit/e9b886033f414a82570a76e4d0c3a366dae99aec

To reproduce:
* `cd /tmp` (or any other directory ;))
* `wget http://maven.xwiki.org/releases/org/xwiki/platform/xwiki-platform-distribution-war/14.8-rc-1/xwiki-platform-distribution-war-14.8-rc-1.war`
* `mkdir xwiki; cf xwiki`
* `jar xvf ../xwiki-platform-distribution-war-14.8-rc-1.war`
* `docker run -v /tmp/xwiki:/var/lib/jetty/webapps/xwiki -p 8080:8080 jetty:10-jdk11`

Thanks for any help on this!

PS: Issue originally created at https://github.com/eclipse/jetty.project/issues/8622 (wrongly).

**Comment by lachlan-roberts** [comment]
@vmassol thanks did manage to reproduce it now, so will look into this soon.

**Comment by vmassol** [comment]
@lachlan-roberts this is awesome, thanks a lot!
