### ISSUE TITLE
jetty docker usage

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#4]
<a href="https://github.com/jeremypumphrey"><img src="https://avatars3.githubusercontent.com/u/8714624?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeremypumphrey](https://github.com/jeremypumphrey)**
_Monday Jun 20, 2016 at 15:54 GMT_
_Originally opened as https://github.com/appropriate/docker-jetty/issues/35_

----

I'm trying to use jetty to deploy a 1.7 war file. My Dockerfile has only this:
FROM jetty:jre7
ADD  target/match-rules.war /var/lib/jetty/webapps/

The docker container starts
95fcb5134f70        matchbox/nci-match-rules   "/docker-entrypoint.s"   15 seconds ago      Up 14 seconds       0.0.0.0:8080->8080/tcp, 0.0.0.0:10250->10250/tcp   Rules

Is this correct or should I copy the CMD line from the jetty Dockerfile as well? I'm having a problem with the war extraction, but it might be unrelated to the Docker usage.  

2016-06-20 15:02:21.631:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:/var/lib/jetty/webapps/] at interval 1
2016-06-20 15:02:29.313:WARN:oejw.StandardDescriptorProcessor:main: Could not instantiate listener org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap
java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
 ...
2016-06-20 15:02:29.687:INFO:nci-match-rules:main: No Spring WebApplicationInitializer types detected on classpath
15:02:29,773 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:02:29,773 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]

**Comment by joakime** [comment]
<a href="https://github.com/md5"><img src="https://avatars0.githubusercontent.com/u/76367?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [md5](https://github.com/md5)**
_Monday Jun 20, 2016 at 16:43 GMT_

----

You don't need to add a `CMD` line to your own Dockerfile. These lines look suspect:

> 2016-06-20 15:02:29.313:WARN:oejw.StandardDescriptorProcessor:main: Could not instantiate listener org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap
> java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap
> at java.net.URLClassLoader$1.run(URLClassLoader.java:366)

**Comment by joakime** [comment]
<a href="https://github.com/mmorejon"><img src="https://avatars1.githubusercontent.com/u/5578317?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmorejon](https://github.com/mmorejon)**
_Thursday Jul 13, 2017 at 19:31 GMT_

----

I have the same problem. Any suggestion?
